name: Deploy to staging
on:
  push:
    branches:
      - main

jobs:
  redeploy_app:
    name: Deploying the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Running on host:"
            uname -a
            cd ci-cd
            git pull
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20
            pnpm install
            pnpm run build
            pm2 restart backend
            pm2 restart frontend  
            pm2 restart web-socket 
